language: nix
sudo: false

matrix:
  include:
    - os: linux
      script:
        - nix-build
    - os: osx
      script:
        - nix-build
env:
  global:
    - GITHUB_TOKEN=5edaaf1017f691ed34e7f80878f8f5fbd071603f
